/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as ArchitectureAtlasRouteImport } from './routes/architecture-atlas'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as BlueprintRouteImport } from './routes/blueprint'
import { Route as BookshelfRouteImport } from './routes/bookshelf'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as DecisionRoomRouteImport } from './routes/decision-room'
import { Route as EngineeringRouteImport } from './routes/engineering'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as FailureMuseumRouteImport } from './routes/failure-museum'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as InnovationLabRouteImport } from './routes/innovation-lab'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LabRouteImport } from './routes/lab'
import { Route as MissionControlRouteImport } from './routes/mission-control'
import { Route as MissionHistoryRouteImport } from './routes/mission-history'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as NowRouteImport } from './routes/now'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PromptLabRouteImport } from './routes/prompt-lab'
import { Route as ResearchVaultRouteImport } from './routes/research-vault'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as UsesRouteImport } from './routes/uses'
import { Route as WorkflowRouteImport } from './routes/workflow'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureAtlasRoute = ArchitectureAtlasRouteImport.update({
  id: '/architecture-atlas',
  path: '/architecture-atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const BlueprintRoute = BlueprintRouteImport.update({
  id: '/blueprint',
  path: '/blueprint',
  getParentRoute: () => rootRouteImport,
} as any)
const BookshelfRoute = BookshelfRouteImport.update({
  id: '/bookshelf',
  path: '/bookshelf',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionRoomRoute = DecisionRoomRouteImport.update({
  id: '/decision-room',
  path: '/decision-room',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringRoute = EngineeringRouteImport.update({
  id: '/engineering',
  path: '/engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const FailureMuseumRoute = FailureMuseumRouteImport.update({
  id: '/failure-museum',
  path: '/failure-museum',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovationLabRoute = InnovationLabRouteImport.update({
  id: '/innovation-lab',
  path: '/innovation-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionControlRoute = MissionControlRouteImport.update({
  id: '/mission-control',
  path: '/mission-control',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionHistoryRoute = MissionHistoryRouteImport.update({
  id: '/mission-history',
  path: '/mission-history',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const NowRoute = NowRouteImport.update({
  id: '/now',
  path: '/now',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptLabRoute = PromptLabRouteImport.update({
  id: '/prompt-lab',
  path: '/prompt-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchVaultRoute = ResearchVaultRouteImport.update({
  id: '/research-vault',
  path: '/research-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const UsesRoute = UsesRouteImport.update({
  id: '/uses',
  path: '/uses',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/architecture-atlas': typeof ArchitectureAtlasRoute
  '/archive': typeof ArchiveRoute
  '/atlas': typeof AtlasRoute
  '/blueprint': typeof BlueprintRoute
  '/bookshelf': typeof BookshelfRoute
  '/case-studies': typeof CaseStudiesRoute
  '/decision-room': typeof DecisionRoomRoute
  '/engineering': typeof EngineeringRoute
  '/experience': typeof ExperienceRoute
  '/failure-museum': typeof FailureMuseumRoute
  '/faq': typeof FaqRoute
  '/innovation-lab': typeof InnovationLabRoute
  '/journal': typeof JournalRoute
  '/lab': typeof LabRoute
  '/mission-control': typeof MissionControlRoute
  '/mission-history': typeof MissionHistoryRoute
  '/notebook': typeof NotebookRoute
  '/now': typeof NowRoute
  '/passport': typeof PassportRoute
  '/profile': typeof ProfileRoute
  '/prompt-lab': typeof PromptLabRoute
  '/research-vault': typeof ResearchVaultRoute
  '/resources': typeof ResourcesRoute
  '/roadmap': typeof RoadmapRoute
  '/uses': typeof UsesRoute
  '/workflow': typeof WorkflowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/architecture-atlas': typeof ArchitectureAtlasRoute
  '/archive': typeof ArchiveRoute
  '/atlas': typeof AtlasRoute
  '/blueprint': typeof BlueprintRoute
  '/bookshelf': typeof BookshelfRoute
  '/case-studies': typeof CaseStudiesRoute
  '/decision-room': typeof DecisionRoomRoute
  '/engineering': typeof EngineeringRoute
  '/experience': typeof ExperienceRoute
  '/failure-museum': typeof FailureMuseumRoute
  '/faq': typeof FaqRoute
  '/innovation-lab': typeof InnovationLabRoute
  '/journal': typeof JournalRoute
  '/lab': typeof LabRoute
  '/mission-control': typeof MissionControlRoute
  '/mission-history': typeof MissionHistoryRoute
  '/notebook': typeof NotebookRoute
  '/now': typeof NowRoute
  '/passport': typeof PassportRoute
  '/profile': typeof ProfileRoute
  '/prompt-lab': typeof PromptLabRoute
  '/research-vault': typeof ResearchVaultRoute
  '/resources': typeof ResourcesRoute
  '/roadmap': typeof RoadmapRoute
  '/uses': typeof UsesRoute
  '/workflow': typeof WorkflowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/architecture-atlas': typeof ArchitectureAtlasRoute
  '/archive': typeof ArchiveRoute
  '/atlas': typeof AtlasRoute
  '/blueprint': typeof BlueprintRoute
  '/bookshelf': typeof BookshelfRoute
  '/case-studies': typeof CaseStudiesRoute
  '/decision-room': typeof DecisionRoomRoute
  '/engineering': typeof EngineeringRoute
  '/experience': typeof ExperienceRoute
  '/failure-museum': typeof FailureMuseumRoute
  '/faq': typeof FaqRoute
  '/innovation-lab': typeof InnovationLabRoute
  '/journal': typeof JournalRoute
  '/lab': typeof LabRoute
  '/mission-control': typeof MissionControlRoute
  '/mission-history': typeof MissionHistoryRoute
  '/notebook': typeof NotebookRoute
  '/now': typeof NowRoute
  '/passport': typeof PassportRoute
  '/profile': typeof ProfileRoute
  '/prompt-lab': typeof PromptLabRoute
  '/research-vault': typeof ResearchVaultRoute
  '/resources': typeof ResourcesRoute
  '/roadmap': typeof RoadmapRoute
  '/uses': typeof UsesRoute
  '/workflow': typeof WorkflowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/architecture-atlas'
    | '/archive'
    | '/atlas'
    | '/blueprint'
    | '/bookshelf'
    | '/case-studies'
    | '/decision-room'
    | '/engineering'
    | '/experience'
    | '/failure-museum'
    | '/faq'
    | '/innovation-lab'
    | '/journal'
    | '/lab'
    | '/mission-control'
    | '/mission-history'
    | '/notebook'
    | '/now'
    | '/passport'
    | '/profile'
    | '/prompt-lab'
    | '/research-vault'
    | '/resources'
    | '/roadmap'
    | '/uses'
    | '/workflow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/architecture-atlas'
    | '/archive'
    | '/atlas'
    | '/blueprint'
    | '/bookshelf'
    | '/case-studies'
    | '/decision-room'
    | '/engineering'
    | '/experience'
    | '/failure-museum'
    | '/faq'
    | '/innovation-lab'
    | '/journal'
    | '/lab'
    | '/mission-control'
    | '/mission-history'
    | '/notebook'
    | '/now'
    | '/passport'
    | '/profile'
    | '/prompt-lab'
    | '/research-vault'
    | '/resources'
    | '/roadmap'
    | '/uses'
    | '/workflow'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/architecture-atlas'
    | '/archive'
    | '/atlas'
    | '/blueprint'
    | '/bookshelf'
    | '/case-studies'
    | '/decision-room'
    | '/engineering'
    | '/experience'
    | '/failure-museum'
    | '/faq'
    | '/innovation-lab'
    | '/journal'
    | '/lab'
    | '/mission-control'
    | '/mission-history'
    | '/notebook'
    | '/now'
    | '/passport'
    | '/profile'
    | '/prompt-lab'
    | '/research-vault'
    | '/resources'
    | '/roadmap'
    | '/uses'
    | '/workflow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  ArchitectureAtlasRoute: typeof ArchitectureAtlasRoute
  ArchiveRoute: typeof ArchiveRoute
  AtlasRoute: typeof AtlasRoute
  BlueprintRoute: typeof BlueprintRoute
  BookshelfRoute: typeof BookshelfRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  DecisionRoomRoute: typeof DecisionRoomRoute
  EngineeringRoute: typeof EngineeringRoute
  ExperienceRoute: typeof ExperienceRoute
  FailureMuseumRoute: typeof FailureMuseumRoute
  FaqRoute: typeof FaqRoute
  InnovationLabRoute: typeof InnovationLabRoute
  JournalRoute: typeof JournalRoute
  LabRoute: typeof LabRoute
  MissionControlRoute: typeof MissionControlRoute
  MissionHistoryRoute: typeof MissionHistoryRoute
  NotebookRoute: typeof NotebookRoute
  NowRoute: typeof NowRoute
  PassportRoute: typeof PassportRoute
  ProfileRoute: typeof ProfileRoute
  PromptLabRoute: typeof PromptLabRoute
  ResearchVaultRoute: typeof ResearchVaultRoute
  ResourcesRoute: typeof ResourcesRoute
  RoadmapRoute: typeof RoadmapRoute
  UsesRoute: typeof UsesRoute
  WorkflowRoute: typeof WorkflowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture-atlas': {
      id: '/architecture-atlas'
      path: '/architecture-atlas'
      fullPath: '/architecture-atlas'
      preLoaderRoute: typeof ArchitectureAtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blueprint': {
      id: '/blueprint'
      path: '/blueprint'
      fullPath: '/blueprint'
      preLoaderRoute: typeof BlueprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookshelf': {
      id: '/bookshelf'
      path: '/bookshelf'
      fullPath: '/bookshelf'
      preLoaderRoute: typeof BookshelfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision-room': {
      id: '/decision-room'
      path: '/decision-room'
      fullPath: '/decision-room'
      preLoaderRoute: typeof DecisionRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering': {
      id: '/engineering'
      path: '/engineering'
      fullPath: '/engineering'
      preLoaderRoute: typeof EngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/failure-museum': {
      id: '/failure-museum'
      path: '/failure-museum'
      fullPath: '/failure-museum'
      preLoaderRoute: typeof FailureMuseumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovation-lab': {
      id: '/innovation-lab'
      path: '/innovation-lab'
      fullPath: '/innovation-lab'
      preLoaderRoute: typeof InnovationLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-control': {
      id: '/mission-control'
      path: '/mission-control'
      fullPath: '/mission-control'
      preLoaderRoute: typeof MissionControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-history': {
      id: '/mission-history'
      path: '/mission-history'
      fullPath: '/mission-history'
      preLoaderRoute: typeof MissionHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now': {
      id: '/now'
      path: '/now'
      fullPath: '/now'
      preLoaderRoute: typeof NowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-lab': {
      id: '/prompt-lab'
      path: '/prompt-lab'
      fullPath: '/prompt-lab'
      preLoaderRoute: typeof PromptLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-vault': {
      id: '/research-vault'
      path: '/research-vault'
      fullPath: '/research-vault'
      preLoaderRoute: typeof ResearchVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uses': {
      id: '/uses'
      path: '/uses'
      fullPath: '/uses'
      preLoaderRoute: typeof UsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  ArchitectureAtlasRoute: ArchitectureAtlasRoute,
  ArchiveRoute: ArchiveRoute,
  AtlasRoute: AtlasRoute,
  BlueprintRoute: BlueprintRoute,
  BookshelfRoute: BookshelfRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  DecisionRoomRoute: DecisionRoomRoute,
  EngineeringRoute: EngineeringRoute,
  ExperienceRoute: ExperienceRoute,
  FailureMuseumRoute: FailureMuseumRoute,
  FaqRoute: FaqRoute,
  InnovationLabRoute: InnovationLabRoute,
  JournalRoute: JournalRoute,
  LabRoute: LabRoute,
  MissionControlRoute: MissionControlRoute,
  MissionHistoryRoute: MissionHistoryRoute,
  NotebookRoute: NotebookRoute,
  NowRoute: NowRoute,
  PassportRoute: PassportRoute,
  ProfileRoute: ProfileRoute,
  PromptLabRoute: PromptLabRoute,
  ResearchVaultRoute: ResearchVaultRoute,
  ResourcesRoute: ResourcesRoute,
  RoadmapRoute: RoadmapRoute,
  UsesRoute: UsesRoute,
  WorkflowRoute: WorkflowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
