/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as BookshelfRouteImport } from './routes/bookshelf'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EngineeringRouteImport } from './routes/engineering'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LabRouteImport } from './routes/lab'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as NowRouteImport } from './routes/now'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as UsesRouteImport } from './routes/uses'
import { Route as WorkRouteImport } from './routes/work'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as WritingRouteImport } from './routes/writing'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const BookshelfRoute = BookshelfRouteImport.update({
  id: '/bookshelf',
  path: '/bookshelf',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringRoute = EngineeringRouteImport.update({
  id: '/engineering',
  path: '/engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const NowRoute = NowRouteImport.update({
  id: '/now',
  path: '/now',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const UsesRoute = UsesRouteImport.update({
  id: '/uses',
  path: '/uses',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/architecture': typeof ArchitectureRoute
  '/atlas': typeof AtlasRoute
  '/bookshelf': typeof BookshelfRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/engineering': typeof EngineeringRoute
  '/faq': typeof FaqRoute
  '/lab': typeof LabRoute
  '/notebook': typeof NotebookRoute
  '/now': typeof NowRoute
  '/playground': typeof PlaygroundRoute
  '/resources': typeof ResourcesRoute
  '/resume': typeof ResumeRoute
  '/roadmap': typeof RoadmapRoute
  '/timeline': typeof TimelineRoute
  '/uses': typeof UsesRoute
  '/work': typeof WorkRoute
  '/workflow': typeof WorkflowRoute
  '/writing': typeof WritingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/architecture': typeof ArchitectureRoute
  '/atlas': typeof AtlasRoute
  '/bookshelf': typeof BookshelfRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/engineering': typeof EngineeringRoute
  '/faq': typeof FaqRoute
  '/lab': typeof LabRoute
  '/notebook': typeof NotebookRoute
  '/now': typeof NowRoute
  '/playground': typeof PlaygroundRoute
  '/resources': typeof ResourcesRoute
  '/resume': typeof ResumeRoute
  '/roadmap': typeof RoadmapRoute
  '/timeline': typeof TimelineRoute
  '/uses': typeof UsesRoute
  '/work': typeof WorkRoute
  '/workflow': typeof WorkflowRoute
  '/writing': typeof WritingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/architecture': typeof ArchitectureRoute
  '/atlas': typeof AtlasRoute
  '/bookshelf': typeof BookshelfRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/engineering': typeof EngineeringRoute
  '/faq': typeof FaqRoute
  '/lab': typeof LabRoute
  '/notebook': typeof NotebookRoute
  '/now': typeof NowRoute
  '/playground': typeof PlaygroundRoute
  '/resources': typeof ResourcesRoute
  '/resume': typeof ResumeRoute
  '/roadmap': typeof RoadmapRoute
  '/timeline': typeof TimelineRoute
  '/uses': typeof UsesRoute
  '/work': typeof WorkRoute
  '/workflow': typeof WorkflowRoute
  '/writing': typeof WritingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/architecture'
    | '/atlas'
    | '/bookshelf'
    | '/case-studies'
    | '/contact'
    | '/engineering'
    | '/faq'
    | '/lab'
    | '/notebook'
    | '/now'
    | '/playground'
    | '/resources'
    | '/resume'
    | '/roadmap'
    | '/timeline'
    | '/uses'
    | '/work'
    | '/workflow'
    | '/writing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/architecture'
    | '/atlas'
    | '/bookshelf'
    | '/case-studies'
    | '/contact'
    | '/engineering'
    | '/faq'
    | '/lab'
    | '/notebook'
    | '/now'
    | '/playground'
    | '/resources'
    | '/resume'
    | '/roadmap'
    | '/timeline'
    | '/uses'
    | '/work'
    | '/workflow'
    | '/writing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/architecture'
    | '/atlas'
    | '/bookshelf'
    | '/case-studies'
    | '/contact'
    | '/engineering'
    | '/faq'
    | '/lab'
    | '/notebook'
    | '/now'
    | '/playground'
    | '/resources'
    | '/resume'
    | '/roadmap'
    | '/timeline'
    | '/uses'
    | '/work'
    | '/workflow'
    | '/writing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  ArchitectureRoute: typeof ArchitectureRoute
  AtlasRoute: typeof AtlasRoute
  BookshelfRoute: typeof BookshelfRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  EngineeringRoute: typeof EngineeringRoute
  FaqRoute: typeof FaqRoute
  LabRoute: typeof LabRoute
  NotebookRoute: typeof NotebookRoute
  NowRoute: typeof NowRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ResourcesRoute: typeof ResourcesRoute
  ResumeRoute: typeof ResumeRoute
  RoadmapRoute: typeof RoadmapRoute
  TimelineRoute: typeof TimelineRoute
  UsesRoute: typeof UsesRoute
  WorkRoute: typeof WorkRoute
  WorkflowRoute: typeof WorkflowRoute
  WritingRoute: typeof WritingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookshelf': {
      id: '/bookshelf'
      path: '/bookshelf'
      fullPath: '/bookshelf'
      preLoaderRoute: typeof BookshelfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering': {
      id: '/engineering'
      path: '/engineering'
      fullPath: '/engineering'
      preLoaderRoute: typeof EngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/now': {
      id: '/now'
      path: '/now'
      fullPath: '/now'
      preLoaderRoute: typeof NowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uses': {
      id: '/uses'
      path: '/uses'
      fullPath: '/uses'
      preLoaderRoute: typeof UsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  ArchitectureRoute: ArchitectureRoute,
  AtlasRoute: AtlasRoute,
  BookshelfRoute: BookshelfRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  EngineeringRoute: EngineeringRoute,
  FaqRoute: FaqRoute,
  LabRoute: LabRoute,
  NotebookRoute: NotebookRoute,
  NowRoute: NowRoute,
  PlaygroundRoute: PlaygroundRoute,
  ResourcesRoute: ResourcesRoute,
  ResumeRoute: ResumeRoute,
  RoadmapRoute: RoadmapRoute,
  TimelineRoute: TimelineRoute,
  UsesRoute: UsesRoute,
  WorkRoute: WorkRoute,
  WorkflowRoute: WorkflowRoute,
  WritingRoute: WritingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
